# Generated by Django 4.1.4 on 2023-01-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieTitle', models.CharField(max_length=255)),
                ('MovieIMG', models.CharField(max_length=255)),
                ('MovieDesc', models.TextField()),
                ('Book', models.BooleanField()),
            ],
        ),
    ]
