# Generated by Django 4.1.4 on 2023-01-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BMS',
            new_name='Movie',
        ),
    ]
