# Generated by Django 4.1.5 on 2023-01-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0007_alter_movie_movieimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TName', models.CharField(max_length=255)),
                ('TAddress', models.TextField()),
                ('TCity', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.DateTimeField()),
                ('Mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMS.movie')),
                ('Tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMS.theater')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stime', models.DateTimeField()),
                ('SeatNo', models.IntegerField()),
                ('Mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMS.movie')),
                ('Sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMS.show')),
                ('Tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMS.theater')),
                ('Uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMS.user')),
            ],
        ),
    ]
