# Generated by Django 4.1.5 on 2023-01-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0008_theater_user_show_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='MovieTitle',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
