# Generated by Django 4.1.5 on 2023-01-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0009_alter_movie_movietitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.EmailField(max_length=254),
        ),
    ]
