# Generated by Django 4.1.5 on 2023-01-07 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0010_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Password',
        ),
    ]
