# Generated by Django 4.1.5 on 2023-01-20 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0014_movie_movieintro_alter_movie_movieimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='Seats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
