# Generated by Django 4.1.5 on 2023-01-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0016_remove_show_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='Seats',
            field=models.IntegerField(default=0),
        ),
    ]
