# Generated by Django 4.1.5 on 2023-01-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0017_show_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='Seats',
        ),
    ]
