# Generated by Django 4.1.5 on 2023-01-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0021_alter_show_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Stime',
        ),
    ]
