# Generated by Django 4.1.5 on 2023-01-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0028_alter_booking_mid_alter_booking_seatno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Mid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Sid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Tid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Uid',
            field=models.CharField(max_length=255),
        ),
    ]
